### ISSUE TITLE
thank me later...

### ISSUE THREAD

**Issue by messi06** [free4soft/v2rayN#1]
https://github.com/messi06/v2rayN/releases/tag/3.9.1

**Comment by free4soft** [comment]
what is it？

**Comment by lao4g8023** [comment]
> https://github.com/messi06/v2rayN/releases/tag/3.9.1

what is it？

**Comment by messi06** [comment]
> > https://github.com/messi06/v2rayN/releases/tag/3.9.1
> 
> what is it？

best v2rayN release , with auto update and ws/tls support , thought to share..
